[FE/회원가입] 회원가입 뷰
STOVE-Milk/steam-clone pull request #12
Opened 2022-01-18 12:17 UTC by ummaeha

2022-01-18 회원가입 뷰 데스크탐 뷰only,,,,
![image](https://user-images.githubusercontent.com/48500209/149935898-cad9ac44-5e82-4c77-80e3-70ff3e266615.png)

2022-01-18 16:31 UTC, ummaeha commented
@minjyo  지호님! navbar 접히는거 들어가면 혹시 깨질까 싶어서 일단 데스크탑 뷰만 만들었는데 nav바 fixed로 들어가있으면 상관없으려나요?

2022-01-19 01:12 UTC, minjyo commented
네 괜찮을 것 같습니다

2022-02-02 08:24 UTC, minjyo requested changes

2022-02-02 08:24 UTC, minjyo commented on src/frontend/components/molecules/AuthInput.tsx
> +export interface IAuthInputProps {
지엽적이긴 한데 인터페이스 위 아래로 엔터..!!

2022-02-02 08:24 UTC, minjyo commented on src/frontend/components/molecules/AuthInput.tsx
> +}: IAuthInputProps) {
이부분 props: IAuthInputProps로 쓰는거랑 같은거 아시죠...!? 양하님처럼 쓰면 밑에서 props.를 안써도 되는 이점도 있구요

2022-02-02 08:24 UTC, minjyo commented on src/frontend/components/molecules/AuthSelectBox.tsx
> +export default function AuthSelectBox({ title, option, onChange }: IOptionProp) {
나중에 리팩토링 할때 이전에 만들어뒀던 atom의 SelectBox를 재사용해서 코드를 작성해보는 것도 좋을것같아요

2022-02-02 08:24 UTC, minjyo commented on src/frontend/pages/signin.tsx
> +  const [errors, setErrors] = useState({} as Record<any, string>);
string이 아닌 Record<>로 정의하신 이유가 있나요?

2022-02-02 08:24 UTC, minjyo commented on src/frontend/pages/signup.tsx
> +      setErrors((prev) => ({ ...prev, email: '이메일을 필수로 입력해주세요' }));
이부분 이해가 잘 안가는데 내일 설명부탁드립니당

2022-02-04 07:14 UTC, ummaeha commented on src/frontend/components/molecules/AuthInput.tsx
> +}: IAuthInputProps) {
아 네네 알고있습니다/ 원래 저렇게 props가 많아질지 모르고 {}로 풀어서쓴건데 밑에 코드들도 다 props. 으로 안 쓰고 풀어서 쓴 상태라 그대로 뒀네요 ~

2022-02-04 07:22 UTC, ummaeha commented on src/frontend/pages/signin.tsx
> +  const [errors, setErrors] = useState({} as Record<any, string>);
전에 참여했던 프로젝트에서 썻던대로 가져왔는데, setError라는 error를 set하는 함수의 타입을 임의대로 key value로 지정하기위해 사용했다고 이해하고 적었습니다. 여기서 사용된 사례들은 다 key값이 string으로 들어가있긴하지만, 확장되면 오류메시지는 항상 string일테지만, key에는 다른 것이 들어갈 수 있다고 생각했습니다.

2022-02-04 07:23 UTC, ummaeha commented on src/frontend/pages/signin.tsx
> +  const [errors, setErrors] = useState({} as Record<any, string>);
지금은 Key가 다 string이라서 Record<string, string>으로 해도 문제는 없을 것 같습니다 :)

2022-02-04 07:24 UTC, ummaeha commented on src/frontend/pages/signup.tsx
> +      setErrors((prev) => ({ ...prev, email: '이메일을 필수로 입력해주세요' }));
이전에 있던 다른쪽에서 set된 에러메시지(key, value)를 보관하기위해 ...prev를 해준것이고 새로추가된 메시지를 뒤에 더한 것 입니다. 이 부분에선는 email에 대한 에러가 발생할 예정이므로, email에러를 추가한 것 입니다.

2022-02-07 11:09 UTC, ummaeha commented
리뷰때 중점적으로 봐주셨으면 좋겠는 부분은 `signup.tsx` 파일 입니다. 
회원가입을 위한 조건들때문에` if `문을 많이 걸어놓았는데, 그 부분을 어떻게 하면 개선할 수 있을지 아이디어 주시면 감사하곘습니다:)

2022-02-08 00:55 UTC, ummaeha commented
@minjyo 
어제 이야기한대로, private routeing 처리는 후순위로 하고, 일단 각 페이지에서 useSelector로 정보를 가져오는 것으로 하겠습니다 :)

2022-02-08 08:10 UTC, minjyo approved these changes

2022-02-08 08:10 UTC, minjyo commented on src/frontend/pages/signin.tsx
> +        const result = JSON.parse(payload.toString());
토큰 파싱하는 부분은 따로 함수로 빼면 깔끔할 것 같아요

2022-02-08 08:10 UTC, minjyo commented on src/frontend/pages/signin.tsx
> +      alert(Object.values(errors));
시간 되실 때 alert한 부분 전부 모달로 사용하셔도 될 것 같습니다.

2022-02-08 08:10 UTC, minjyo commented on src/frontend/pages/signin.tsx
> +  const onChangeSetInfo = (e: any) => {
React.memo !

2022-02-08 08:10 UTC, minjyo commented on src/frontend/pages/signup.tsx
> +    if (!nullChecker) {
회원가입, 로그인할 때 유효값인지 검증하는 로직 자체가 지엽적이라 if문 관련 리팩토링은 힘들거 같은데, 
현재 시점에선 null check하는 부분과 오류 관련 모달(alert를 모달로 바꾼다면)을 유틸로 뺼 수 있을 것 같습니다. 
회원가입, 로그인화면에서 동일하게 쓰이니까요

2022-02-08 12:51 UTC, ummaeha commented on src/frontend/pages/signin.tsx
> +        const result = JSON.parse(payload.toString());
좋은 생각입니다!

2022-02-08 13:04 UTC, ummaeha commented on src/frontend/pages/signin.tsx
> +  const onChangeSetInfo = (e: any) => {
React.memo를 씌워봤는데, 콘솔을 찍어봤을때는 똑같이 onChange이벤트에 따라 렌더링이 되어서, 좀 더 찾아보고 리팩토링때 적용하도록 하겠습니다 :) 노션에 메모해두겠습니다!
![image](https://user-images.githubusercontent.com/48500209/152992516-f0faf05f-bb72-4039-820f-30c2b6f85291.png)

2022-02-08 13:06 UTC, ummaeha commented on src/frontend/pages/signup.tsx
> +    if (!nullChecker) {
조언 감사합니다. 제가 setState함수를 어떻게 util로 뺄지 좀 더 고민해보고 리팩토링때 적용해보도록하겠습니다.

2022-02-08 13:07 UTC, ummaeha commented on src/frontend/pages/signin.tsx
> +      alert(Object.values(errors));
넵 이부분도 리팩토링때 한 번에 진행할게요 ! 지금 제쪽에서 안내메시지를 alert처리해놓은 곳이 은근 많아서요!

2022-02-08 13:08 UTC, merged