[FE/충전페이지] 충전아이템 목록 조회, 충전 요청하기, 충전확인하기
STOVE-Milk/steam-clone pull request #18
Opened 2022-01-22 10:18 UTC by ummaeha

### TO DO

**뷰**
- [ ] 기프트카드 선택하는 UI 만들기 (하나 onclick 되면 다른 것은 해제되게끔)
- [ ] QR 코드 스캔 후 결제 대기화면 

**API 통신**
- [ ] 기프트카드 불러오기` /payment/giftcards/KR`
- [ ] 충전 요청하기 `/payment/charge/ready`
- [ ] 충전 확인 승인하기 `/payment/charge/approve` -> url 에 쿼리로 존재하는 `pg_token`을 부모페이지로 보내는 방법 고민하기

### Preview
![image](https://user-images.githubusercontent.com/48500209/150634261-23b4cef6-174c-4a6c-a82d-c8e8c2b88078.png)

2022-01-26 13:36 UTC, ummaeha commented on src/frontend/.env
> +NEXT_PUBLIC_BASE_URL = http://fortice.co.kr:8080
따옴표가 함께들어가서 없애야 함

2022-02-02 08:16 UTC, minjyo requested changes

2022-02-02 08:16 UTC, minjyo commented on src/frontend/components/atoms/CommonSelectBox.tsx
> +import React from 'react';
SelectBox가 아니라 CommonSelectBox로 하신 이유가 따로 있나요?

2022-02-02 08:16 UTC, minjyo commented on src/frontend/components/molecules/GiftCard.tsx
> +`;
A. 합치는게 맞다고 생각합니다! 스타일드 컴포넌트 내에서만 코드가 조금 복잡해지고 밑에서는 간단해지는 코드가 더 좋은 코드라고 생각해요

2022-02-02 08:16 UTC, minjyo commented on src/frontend/modules/user/reducer.ts
> +    giftCardList: asyncState.success(action.payload.data),
나중에 api 명세보고 수정 필요하겠네요

2022-02-06 07:06 UTC, ummaeha commented
충전쪽 통신 테스트이후 store쪽 이슈가 발견되어 픽스중에 있습니다.
관련 이슈: #47 
- [ ] tid가 사용자에게 노출되면 안되므로 localstorage로 관리하면 안됨

추가적으로 해결중인 부분
- [ ] dispatch 비동기 처리
- [ ] 성공/실패/취소 상황에 따른 redirect
- [ ] 사용자가 선택한 충전금액이 반영되게

2022-02-06 07:07 UTC, ummaeha commented on src/frontend/components/molecules/GiftCard.tsx
> +`;
어떻게 합칠지 고민중에 있습니다!

2022-02-07 13:40 UTC, ummaeha commented
[tid는 store로 pg_token은 localstorage로 관리하면서 충전 완료](https://github.com/STOVE-Milk/steam-clone/pull/18/commits/2b8bcae4c9f1b0b49c547eb35090205a9d0a7812) !! 감격적

<img src="https://media2.giphy.com/media/j0vs5H7Kcz3Pm9LRDa/giphy.gif"/>

2022-02-08 07:15 UTC, ummaeha commented on src/frontend/components/atoms/CommonSelectBox.tsx
> +import React from 'react';
전에만든 selectbox가 범용성이 떨어져서 따로 제작했는데, 리팩토링 주에 추가작업 필요해보입니다

2022-02-08 07:16 UTC, ummaeha commented on src/frontend/modules/user/reducer.ts
> +    giftCardList: asyncState.success(action.payload.data),
혹시 어떤 부분 말씀이신가요? 데이터를 data로 바로줘서 저렇게 두었습니다!
아 initial 데이터부분말씀이신가요?

2022-02-14 10:08 UTC, merged