[FE/category] 통신
STOVE-Milk/steam-clone pull request #28
Opened 2022-01-26 08:31 UTC by ummaeha

2022-01-26 09:30 UTC, ummaeha commented
#29 ISSUE살펴보고있습니다.

2022-01-27 04:50 UTC, minjyo requested changes

2022-01-27 04:50 UTC, minjyo commented on src/frontend/components/atoms/Text.tsx
> +  className?: string;
오잉 공통 컴포넌트네요. 저 props 두개 어디서 사용하나요?

2022-01-27 04:50 UTC, minjyo commented on src/frontend/components/molecules/CategoryList.tsx
> +    border: 1px solid ${(props) => props.theme.colors.activeBg};
border도 ['activeBg']로 통일 부탁드립니다~

2022-01-27 04:50 UTC, minjyo commented on src/frontend/components/organisms/GameInfo.tsx
> +                    icon={eachOs.toLocaleLowerCase().indexOf('window') ? faWindowMaximize : faAppleAlt}
현재 서버에서 데이터 Window로 오고 있지 않나요? 아님 업데이트 전 코드인걸까요?

2022-01-27 04:50 UTC, minjyo commented on src/frontend/modules/game/initalData.ts
> +    '[TEST]역동하는 사냥 본능! 사냥에 새로운 바람을 불러일으킬, 종횡무진으로 도약하는 액션. 마음 가는 대로 달릴 수 있는 필드. 미지의 흥분과 놀라움을 선사할 새로운 몬스터들. 이제껏 없었던 사냥 체험이 「MONSTER HUNTER RISE」에서 헌터들을 기다린다!',
[TEST] 처리하는거 좋은것같습니다 :)

2022-01-27 04:50 UTC, minjyo commented on src/frontend/next.config.js
> +  },
이 부분 내일 설명해주세요!!

2022-01-27 15:39 UTC, ummaeha commented on src/frontend/components/atoms/Text.tsx
> +  className?: string;
onClick과 className은 기본적으로 사용되는 것이라고 생각되어서 넣었고, 카테고리페이지에서 사용됩니다.

2022-01-27 15:41 UTC, ummaeha commented on src/frontend/components/organisms/GameInfo.tsx
> +                    icon={eachOs.toLocaleLowerCase().indexOf('window') ? faWindowMaximize : faAppleAlt}
`Window`로 오고있는데, 이 값이 `windows` 혹은 `window10` 로 바뀌더라도 처리될수있도록 짠 코드입니다.
먼저 서버에서 온 데이터를 다 소문자로 바꾼 후에 `window`를 찾고 있으면 `windows`아이콘을 없으면 `apple` 아이콘을 반환합니다.

2022-01-27 15:44 UTC, ummaeha commented on src/frontend/next.config.js
> +  },
간단하게 설명하자면, 지금 서버에서 이미지와 동영상은 `"https://cdn.akamai.steamstatic.com/steam/apps/256864285/movie480_vp9.webm?t=1640223329"`
위와같은  도메인을 가진 형태로 오는데, 그 중 `baseurl`을` next.config.js` 에 넣어줘야 오류없이 잘 돌아갑니다.(공식문서 참고)

2022-02-01 17:19 UTC, ummaeha commented
Advanced(이 PR에서 해결할 문제가 아니므로 이슈를 남긴채 다음으로 넘김)

 [FE/ 환경설정] DOM요소에 변화가 있을 때 화면이 깜빡 거리는 현상 #29 이슈해결하기
 [FE / nextjs] 렌더링하면 데이터가 undefined 로 뜨는 문제 #27 &&연산자 없이 undefined 처리하기

2022-02-01 17:20 UTC, merged