공통 컴포넌트 개발
STOVE-Milk/steam-clone pull request #3
Opened 2021-12-29 03:08 UTC by minjyo

2022-01-11 06:59 UTC, ummaeha commented
https://github.com/STOVE-Milk/steam-clone/pull/3/commits/c104ff1f4a9d7d33017dc6255eccd92c0886dfaa
json-server는 npm start로 실행하시면 됩니다. 
4001번 포트를 사용하고있고, API 명세 파일 참고하여 db.json파일에 데이터베이스를 작성하면 됩니다.
(일단 서버개발자분꼐 mock 데이터까지 요청드린 상태)

2022-01-13 03:59 UTC, ummaeha requested changes

2022-01-13 03:59 UTC, ummaeha commented on src/frontend/components/molecules/FriendBox.tsx
> +  flex: 1;
저는 flex:1 을 잘 사용하지 않았는데, 지호님 덕분에 알아갑니다 :)

2022-01-13 03:59 UTC, ummaeha commented on src/frontend/components/molecules/GameSlide.tsx
> +  width: 200px;
px로 고정되는 부분에 대해 이야기 나눠봐야할 것 같아요. 반응형 제작하기 시작하면 px 고정이 방해될 수 있을 것 같습니다.

2022-01-13 03:59 UTC, ummaeha commented on src/frontend/components/molecules/GameSlide.tsx
> +        <Info types="tiny">{`$ ${props.info.price}`}</Info>
javascript의 toLocaleString() 메서드를 사용해보세요. 돈 단위와 세자리 단위에 따른 쉼표처리를 해줍니다.
필요에따라 함수화 해서 여러군데서 씌워서 사용해도 될 것 같습니다.

https://www.w3schools.com/jsref/jsref_tolocalestring_number.asp

2022-01-13 03:59 UTC, ummaeha commented on src/frontend/components/molecules/SearchBox.tsx
> +import React, { useState, useCallback, useMemo } from 'react';
제껀데... useMemo안쓰니 지우도록 하겠습니다. @ummaeha

2022-01-13 03:59 UTC, ummaeha commented on src/frontend/components/organisms/Carousel.tsx
> +    margin-left: -3%;
마이너스 마진으로 위치조절을 하다니 독특하네요.!

2022-01-13 03:59 UTC, ummaeha commented on src/frontend/pages/_app.tsx
> +      <Layout>
👍

2022-01-13 03:59 UTC, ummaeha commented on src/frontend/package.json
> +    "react-konva": "^17.0.2-5",
konva 설치를 하셨군요!!!

2022-01-13 03:59 UTC, ummaeha commented on src/frontend/components/organisms/map.tsx
> +import { Stage, Layer, Circle } from 'react-konva';
konva관련 테스트 파일은 common 브랜치에서 제외해야할 것 같습니다 :)

2022-01-13 04:00 UTC, minjyo commented on src/frontend/components/molecules/GameSlide.tsx
> +  width: 200px;
네 이 부분은 Carousel 라이브러리 내에서 Item을 반응형 처리를 자동으로 해주어서, width: 100%;로 변경했습니다!

2022-01-13 04:02 UTC, minjyo commented on src/frontend/components/molecules/GameSlide.tsx
> +        <Info types="tiny">{`$ ${props.info.price}`}</Info>
오 이런게 있네요! 
저희 앞으로 게임 가격 관련해서 많이 쓰일거같으니 util 안에 만들어두겠습니다!

2022-01-13 04:03 UTC, minjyo commented on src/frontend/components/organisms/map.tsx
> +import { Stage, Layer, Circle } from 'react-konva';
네 지우고 다시 커밋하겠습니다~

2022-01-13 05:01 UTC, minjyo commented on src/frontend/components/atoms/DefaultButton.tsx
> +  padding: 0.25em 1em;
이 부분 rem 으로 다시 수정할까요?

2022-01-13 05:01 UTC, minjyo commented on src/frontend/components/atoms/FilledButton.tsx
> +  padding: 0.25em 1em;
rem !

2022-01-13 05:01 UTC, minjyo commented on src/frontend/components/molecules/SearchBox.tsx
> +    setInputText(searchText);
저는 이 부분 querySelector보다는 
(e) => {
  const searchText = e.target.value; 
}
로 작성해요. selector를 쓰려면 또 선택자를 찾아봐야하니까..

2022-01-13 05:01 UTC, minjyo commented on src/frontend/components/molecules/SearchBox.tsx
> +export default function Search({ option, inputText, setOption, setInputText }: ISearchbox) {
export default 하는 컴포넌트명이랑 파일이름이랑 통일시켜주세요~!

2022-01-13 06:40 UTC, ummaeha approved these changes

2022-01-13 06:41 UTC, merged