[FE/Category] Category페이지, GameInfo 컴포넌트
STOVE-Milk/steam-clone pull request #4
Opened 2022-01-14 09:02 UTC by ummaeha

Category페이지, GameInfo 컴포넌트 반응형 뷰 PR 입니다.

**Desktop view**

![image](https://user-images.githubusercontent.com/48500209/149488121-14218f0d-495b-4043-9692-453e73b8bb9c.png)

**Tablet view**

![image](https://user-images.githubusercontent.com/48500209/149488236-d1217117-d77c-4131-aa95-79b07b1ebbb3.png)

**Mobile view**

![image](https://user-images.githubusercontent.com/48500209/149488290-530934bb-9c7d-4073-94e8-dd04e544e148.png)

2022-01-14 11:58 UTC, Tae-Hyeon commented
일 더 많이 맡겨도 되겠네요

2022-01-14 12:23 UTC, abc7468 requested changes
장성현 의문의 1패

2022-01-14 12:23 UTC, abc7468 commented on src/frontend/pages/category.tsx
> +      kr: 20000,
국가 코드 대문자로 맞춥시다! kr -> KR

2022-01-14 13:05 UTC, ummaeha commented on src/frontend/pages/category.tsx
> +      kr: 20000,
리뷰 감사합니다. 완료후 커밋 올렸습니다 :)

2022-01-15 08:55 UTC, abc7468 approved these changes

2022-01-17 05:09 UTC, minjyo requested changes

2022-01-17 05:09 UTC, minjyo commented on src/frontend/components/organisms/GameInfo.tsx
> +  -webkit-box-orient: vertical;
-webkit 외에 다른 브라우저 고려도 하시나요?

2022-01-17 05:09 UTC, minjyo commented on src/frontend/components/organisms/GameInfo.tsx
> +                <FontAwesomeIcon icon={faAppleAlt} inverse />
1. icon = {eachOs === 'windows' ? faWindowMaximize : faAppleAlt} 로 하면 코드가 더 깔끔해질 것 같아요! 
2. == 대신 === 쓰는게 좋을 것 같습니다.

2022-01-17 05:09 UTC, minjyo commented on src/frontend/components/organisms/GameInfo.tsx
> +          </div>
1. true 일 때 <> </> 로 감싸주는데 201줄에서 div 태그가 필요할까요?
2. Boolean(gameDate.sale) 부분 다시 알아보겠습니다~

2022-01-17 05:09 UTC, minjyo commented on src/frontend/pages/index.tsx
> +                  price: data.price.KR,
이후에 리덕스 세팅되면 user 스토어에 country로 넣어서 나중에 data.price[user.country]로 바꾸면 편할거에요

2022-01-17 05:09 UTC, minjyo commented on src/frontend/styles/global-styles.ts
> +  }
아주 좋습니다~!

2022-01-17 05:14 UTC, ummaeha commented on src/frontend/components/organisms/GameInfo.tsx
> +  -webkit-box-orient: vertical;
https://developer.mozilla.org/ko/docs/Web/CSS/-webkit-line-clamp

IE제외 적용됩니다.

2022-01-18 02:02 UTC, ummaeha commented on src/frontend/pages/index.tsx
> +                  price: data.price.KR,
이부분 약간 하드코딩 되어있었는데, 조언 감사합니다 :-)

2022-01-18 02:06 UTC, ummaeha commented on src/frontend/components/organisms/GameInfo.tsx
> +          </div>
div유:
 ![image](https://user-images.githubusercontent.com/48500209/149858021-ede420e8-ceca-42f5-be46-5223ee78a8b4.png)
div무:
 ![image](https://user-images.githubusercontent.com/48500209/149858131-d288db31-dd36-4e9a-9e5e-8f46b6d8501a.png)
 
1. div에 스타일링 요소를 포함시켜 놓아서 필요합니다!
2. typescript에서 boolean으로  정의된 값임에도 불구하고 코드가 잘 안되어서 Boolean으로 강제변경해서 해결했는데, 좀 더 알아보겠습니다. (이상한 점은 typeof gameData.sale 찍어보면 true/false로 boolean 값이 나옵니다.. 예상하기로는 리터럴 이런 문제일것같긴합니다.!)

2022-01-18 02:46 UTC, minjyo approved these changes

2022-01-18 02:46 UTC, merged